# Generated by Django 2.0.3 on 2018-07-30 01:16

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180325_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(default='admin', max_length=127, unique=True, verbose_name='optional username'),
            preserve_default=False,
        ),
    ]
