# Generated by Django 2.0.3 on 2018-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
