# Generated by Django 2.0.3 on 2018-07-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0002_auto_20180705_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_or_exam',
            field=models.CharField(choices=[('Q', 'Quiz'), ('E', 'Exam')], default='Q', max_length=1),
        ),
    ]
