# Generated by Django 2.0.3 on 2018-03-24 22:03

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The course title', max_length=512, unique=True, verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=64)),
                ('teaser', models.CharField(blank=True, help_text='A brief, one-sentence description of the course.', max_length=512, verbose_name='Course content teaser')),
                ('description', models.CharField(help_text='A description of the course.', max_length=1024, verbose_name='Course description')),
                ('long_description', models.TextField(help_text='A longer description of the course.', verbose_name='Course long description')),
                ('image', models.ImageField(max_length=512, null=True, upload_to='img/courses/')),
                ('status', models.CharField(choices=[('D', 'Deleted'), ('U', 'Unpublished'), ('P', 'Published')], default='U', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The course title', max_length=512, unique=True, verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=64)),
                ('content', models.TextField()),
                ('order_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('D', 'Deleted'), ('U', 'Unpublished'), ('P', 'Published')], default='U', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(help_text='Tag name', max_length=32, unique=True, verbose_name='Tag name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='learn.Tag'),
        ),
    ]
