# Generated by Django 2.0.3 on 2018-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20180325_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=512, upload_to='img/courses/'),
            preserve_default=False,
        ),
    ]
