DROP INDEX quiz_answers_tr_idx;
--;;
DROP TABLE quiz_answers_tr CASCADE;
--;;
DROP TABLE quiz_answers CASCADE;
--;;
DROP INDEX test_answers_tr_idx;
--;;
DROP TABLE test_answers_tr CASCADE;
--;;
DROP TABLE test_answers CASCADE;
--;;
DROP INDEX quiz_questions_tr_idx;
--;;
DROP TABLE quiz_questions_tr CASCADE;
--;;
DROP TABLE quiz_questions CASCADE;
--;;
DROP INDEX test_questions_tr_idx;
--;;
DROP TABLE test_questions_tr CASCADE;
--;;
DROP TABLE test_questions CASCADE;
--;;
DROP TABLE tests CASCADE;
--;;
DROP TABLE quizzes CASCADE;
--;;
DROP TABLE resource_locales CASCADE;
